/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from '../../../../../src/app/components/page-not-found/page-not-found.component';
const styles_PageNotFoundComponent:any[] = ([] as any[]);
export const RenderType_PageNotFoundComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_PageNotFoundComponent,data:{}});
export function View_PageNotFoundComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),17,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          14,'div',[['class','card']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),11,'div',[['class','card-body']],(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n            '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h3',
          [['class','card-title']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['Oooops! Page Not Found'])),
      (_l()(),i0.ɵted((null as any),['\n            '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),5,'p',[['class','card-text']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['The page you are looking for doesn\'t exist. Do you want to start from the '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink','/']],[[1,
          'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,12).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['beginning'])),(_l()(),i0.ɵted((null as any),
          ['?'])),(_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    const currVal_2:any = '/';
    _ck(_v,12,0,currVal_2);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,12).target;
    const currVal_1:any = i0.ɵnov(_v,12).href;
    _ck(_v,11,0,currVal_0,currVal_1);
  });
}
export function View_PageNotFoundComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'page-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_PageNotFoundComponent_0,
      RenderType_PageNotFoundComponent)),i0.ɵdid(49152,(null as any),0,i3.PageNotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PageNotFoundComponentNgFactory:i0.ComponentFactory<i3.PageNotFoundComponent> = i0.ɵccf('page-not-found',
    i3.PageNotFoundComponent,View_PageNotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvSm9oYW5uYS9Bbmd1bGFyUHJvamVjdHMvbXktcG9ydGZvbGlvL3NyYy9hcHAvY29tcG9uZW50cy9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvSm9oYW5uYS9Bbmd1bGFyUHJvamVjdHMvbXktcG9ydGZvbGlvL3NyYy9hcHAvY29tcG9uZW50cy9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9Kb2hhbm5hL0FuZ3VsYXJQcm9qZWN0cy9teS1wb3J0Zm9saW8vc3JjL2FwcC9jb21wb25lbnRzL3BhZ2Utbm90LWZvdW5kL3BhZ2Utbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvSm9oYW5uYS9Bbmd1bGFyUHJvamVjdHMvbXktcG9ydGZvbGlvL3NyYy9hcHAvY29tcG9uZW50cy9wYWdlLW5vdC1mb3VuZC9wYWdlLW5vdC1mb3VuZC5jb21wb25lbnQudHMuUGFnZU5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPGRpdiBjbGFzcz1cImNhcmRcIj5cclxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2FyZC1ib2R5XCI+XHJcbiAgICAgICAgICAgIDxoMyBjbGFzcz1cImNhcmQtdGl0bGVcIj5Pb29vcHMhIFBhZ2UgTm90IEZvdW5kPC9oMz5cclxuICAgICAgICAgICAgPHAgY2xhc3M9XCJjYXJkLXRleHRcIj5UaGUgcGFnZSB5b3UgYXJlIGxvb2tpbmcgZm9yIGRvZXNuJ3QgZXhpc3QuIERvIHlvdSB3YW50IHRvIHN0YXJ0IGZyb20gdGhlIDxhIHJvdXRlckxpbms9XCIvXCI+YmVnaW5uaW5nPC9hPj88L3A+XHJcbiAgICAgICAgPC9kaXY+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+IiwiPHBhZ2Utbm90LWZvdW5kPjwvcGFnZS1ub3QtZm91bmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO01BQXVCLDJDQUNuQjtVQUFBO1VBQUEsZ0JBQWtCLCtDQUNkO1VBQUE7VUFBQSwwREFBdUI7VUFBQSxxQkFDbkI7VUFBQTtVQUFBLGdCQUF1QjtNQUEyQixtREFDbEQ7VUFBQTtVQUFBLDRDQUFxQjtVQUFBO01BQTBFO1VBQUE7UUFBQTtRQUFBO1VBQUE7Y0FBQTtVQUFBO1FBQUE7UUFBQTtNQUFBLHVDQUFBO1VBQUE7VUFBQSxlQUFrQiw4Q0FBYTtVQUFBLFFBQUssK0NBQ2pJO1VBQUEsYUFDSjtJQUZvRztJQUFILFlBQUcsU0FBSDs7SUFBQTtJQUFBO0lBQUEsWUFBQSxtQkFBQTs7OztvQkNKM0c7TUFBQTtzQ0FBQSxVQUFBO01BQUE7OzsifQ==
